BarberShop/Controllers/AppointmentController.cs
using AutoMapper;
using BusinessLogic;
using Enums;
using Helpers.Select2;
using Microsoft.AspNet.Identity;
using Models;
using Models.Identity;
using Models.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Script.Serialization;

namespace BarberShop.Controllers
{
    public class AppointmentController : Controller
    {
        // GET: Appointment
        public ActionResult Index(AppointmentSearchViewModel model)
        {
            if (!string.IsNullOrEmpty(model.TreatmentStatuses))
            {
                try
                {
                    model.MultiAppointmentTreatmentStatus = new List<int>();
                    foreach (var s in model.TreatmentStatuses.Split(','))
                    {
                        model.MultiAppointmentTreatmentStatus.Add((int)Enum.Parse(typeof(AppointmentTreatmentStatus), s));
                    }
                }
                catch
                {

                }
            }
            //added for stylish dashboard, as no authorization is required for that view, therefore this acts as a bypass.
            PartialViewResult check;
            var userId = User.Identity.GetUserId();
            if (Request.UrlReferrer != null)
            {
                var url = Request.UrlReferrer.AbsolutePath;
                if (User.IsInRole("SuperAdministrator") || User.IsInRole("Administrator") || url.Contains("Dashboard"))
                {
                    return View(GetAppointments(model).Model);
                }
                else if (User.IsInRole("Stylist"))
                {
                    model.StylistId = userId;
                }
                else if (User.IsInRole("Client"))
                {
                    model.ClientId = userId;
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            check = GetAppointments(model);
            return View(check.Model);
        }

        public ActionResult AppointmentDashboard()
        {
            var stylistId = User.IsInRole("Stylist") ? User.Identity.GetUserId() : "";
            var stylists = new Logic().GetUsers<RegisterViewModel>(new AccountSearchViewModel { Id = stylistId, RoleId = new Logic().GetRoleId<RoleViewModel>(new RoleSearchViewModel { Name = "Stylist" }).ResultList.FirstOrDefault().Id }).ResultList.GroupBy(x => x.Email).Select(o => o.FirstOrDefault());
            var model = new FullCalendarSchedular { events = new List<FullCalendarEvents>(), resources = new List<FullCalendarResources>() };
            model.resources = stylists.Select(m => new FullCalendarResources { id = m.Id, title = m.Name, eventColor = "transparent" }).Distinct().ToList();
            return View(model);
        }


        public ActionResult AppointmentDetails(FullCalendarEvents EventModel)
        {
            return PartialView("_AppointmentDetails", EventModel);
        }
        public ActionResult AppointmentToolTip(FullCalendarEvents EventModel)
        {
            return PartialView("_AppointmentToolTip", EventModel);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator, Stylist")]
        public ActionResult Create()
        {
            ViewBag.ViewFor = "Create Appointment";
            return View(new AppointmentViewModel { BookingDate = DateTime.Now, AppointmentStartingTime = DateTime.Now, Action = "Create", Client = new ApplicationUser(), ClientsList = new List<SelectListItem>(), StylistsList = new List<SelectListItem>(), TreatmentsList = new List<SelectListItem>() });
        }

        public PartialViewResult CreatePartial(AppointmentViewModel model)
        {
            return PartialView(model);
        }
        public PartialViewResult CreatePartialModal(Guid? Id, DateTime? Date, Guid? StylistId)
        {
            ViewBag.ViewFor = Id == null || Id == new Guid() ? "Modal Create" : "Modal Edit";
            var BookingDate = Date ?? DateTime.Now;
            var stylist = StylistId != null || StylistId != new Guid() ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = StylistId.ToString(), Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            AppointmentViewModel model = new AppointmentViewModel { BookingDate = BookingDate, AppointmentStartingTime = BookingDate, Action = "Create", Client = new ApplicationUser(), ClientsList = new List<SelectListItem>(), StylistsList = stylist, TreatmentsList = new List<SelectListItem>() };
            if (Id != null)
            {
                var AppointmentId = Id ?? new Guid();
                model = new Logic().GetAppointments<AppointmentViewModel>(new AppointmentSearchViewModel { Id = AppointmentId, StartingDateTime = BookingDate, EndingDateTime = BookingDate.AddDays(1).AddMilliseconds(-10), Select2 = false }).ResultList.First();
                model.Action = "Edit";
                model.ClientsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Client.Id, Text = model.Client.Name, Selected = true }) };
                model.TreatmentsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Treatment.Id.ToString(), Text = model.Treatment.Name, Selected = true }) };
                model.StylistsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Stylist.Id, Text = model.Stylist.Name, Selected = true }) };
            }
            model.IsDashboard = true;
            return PartialView("CreatePartial", model);
        }

        public PartialViewResult CreatePartialForStart(Guid? Id, DateTime? Date, string ClientId, string StylistId, DateTime? LastAppointmentEndingDateTime)
        {

            var BookingDate = Date ?? DateTime.Now.Date;
            var lastAppointmentEndingDateTime = LastAppointmentEndingDateTime ?? DateTime.Now;
            ViewBag.ViewFor = Id == null || Id == new Guid() ? "Start Create" : "Start Edit";
            var stylist = !string.IsNullOrEmpty(StylistId) ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = StylistId, Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            var client = !string.IsNullOrEmpty(ClientId) ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = ClientId, Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            AppointmentViewModel model = new AppointmentViewModel { BookingDate = BookingDate, AppointmentStartingTime = lastAppointmentEndingDateTime, Action = "Create", Client = new ApplicationUser { Name = client.FirstOrDefault().Text, Id = ClientId }, ClientId = ClientId, StylistId = StylistId, ClientsList = client, Stylist = new ApplicationUser { Id = StylistId, Name = stylist.FirstOrDefault().Text }, StylistsList = stylist, TreatmentsList = new List<SelectListItem>() };
            if (Id != null)
            {
                var AppointmentId = Id ?? new Guid();
                model = new Logic().GetAppointments<AppointmentViewModel>(new AppointmentSearchViewModel { Id = AppointmentId, StartingDateTime = BookingDate, EndingDateTime = BookingDate.AddDays(1).AddMilliseconds(-10), Select2 = false }).ResultList.First();
                model.Action = "Edit";
                model.ClientsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Client.Id, Text = model.Client.Name, Selected = true }) };
                model.TreatmentsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Treatment.Id.ToString(), Text = model.Treatment.Name, Selected = true }) };
                model.StylistsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Stylist.Id, Text = model.Stylist.Name, Selected = true }) };
            }
            model.IsDashboard = true;
            model.IsForStart = true;
            return PartialView("CreatePartial", model);
        }

        public PartialViewResult CreateMultiTreatmentAppointment(string StylistId)
        {

            var BookingDate = DateTime.Now.Date;
            var currentDateTime = DateTime.Now;
            var stylist = !string.IsNullOrEmpty(StylistId) ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = StylistId, Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            AppointmentViewModel model = new AppointmentViewModel
            {
                BookingDate = BookingDate,
                AppointmentStartingTime = currentDateTime,
                AppointmentEndingTime = currentDateTime,
                ActualStartingTime = currentDateTime,
                ActualEndingTime = currentDateTime,
                Action = "Create",
                StylistId = StylistId,
                Stylist = new ApplicationUser
                {
                    Id = StylistId,
                    Name = stylist.FirstOrDefault().Text
                }
            };
            return PartialView("_MultiTreatmentAppointment", model);
        }

        [HttpPost]
        public ActionResult Create(AppointmentViewModel model)
        {
            ViewBag.ViewFor = "Create Appointment";
            model.Approver = new ApplicationUser { Id = User.Identity.GetUserId() };
            var result = new Logic().Create(model);
            return Json(result != new Guid(), JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public ActionResult CreateMultiAppointment(AppointmentViewModel model)
        {
            model.Approver = new ApplicationUser { Id = User.Identity.GetUserId() };

BarberShop/Controllers/ReportController.cs
using BusinessLogic;
using Enums;
using Microsoft.AspNet.Identity;
using Models;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace BarberShop.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        //public ActionResult Index()
        //{
        //    var result = RenderRazorViewToString(this, "ReportPartialView", new List<AppointmentViewModel>());
        //     var pdfFile = PdfSharpConvert(result);
        //    return Content(result);
        //}

        //public string RenderRazorViewToString(Controller controller, string partialViewName, object model)
        //{
        //    ViewEngineResult result = ViewEngines.Engines.FindPartialView(controller.ControllerContext, partialViewName);
        //    if (result.View != null)
        //    {
        //        controller.ViewData.Model = model;
        //        StringBuilder sb = new StringBuilder();
        //        using(StringWriter sw = new StringWriter())
        //        {
        //            ViewContext viewContext = new ViewContext(controller.ControllerContext, result.View, ViewData, TempData, sw);
        //            result.View.Render(viewContext, sw);
        //            result.ViewEngine.ReleaseView(viewContext, result.View);
        //            return sw.GetStringBuilder().ToString();
        //        }

        //    }

        //    {
        //        ViewEngineResult result1 = ViewEngines.Engines.FindPartialView(controller.ControllerContext, partialViewName);
        //        if (result1.View != null)
        //        {
        //            controller.ViewData.Model = model;
        //            StringBuilder sb = new StringBuilder();
        //            using(StringWriter sw = new StringWriter(sb))
        //            {
        //                using(HtmlTextWriter output = new HtmlTextWriter(sw))
        //                {
        //                    ViewContext viewContext = new ViewContext(controller.ControllerContext, result.View, ViewData, TempData, output);
        //                    result.View.Render(viewContext, output);
        //                    var html = sb.ToString();
        //                }
        //            }
        //        }
        //    }
        //    return "";
        //}

        //public PartialViewResult ReportPartialView()
        //{
        //    var records = new Logic().GetAppointments<AppointmentViewModel>(new AppointmentSearchViewModel { BookingDate = DateTime.Now, Status = AppointmentStatus.Approved, AppointmentTreatmentStatus = AppointmentTreatmentStatus.Ended }).ResultList;
        //    return PartialView(records);
        //}

        //public static Byte[] PdfSharpConvert(String html)
        //{
        //    Byte[] res = null;
        //    using (MemoryStream ms = new MemoryStream())
        //    {
        //        var pdf = TheArtOfDev.HtmlRenderer.PdfSharp.PdfGenerator.GeneratePdf(html, PdfSharp.PageSize.A4);
        //        pdf.Save(ms);
        //        res = ms.ToArray();
        //    }
        //    return res;
        //}

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult GetTreatmentReport()
        {
            return View();
        }

        public PartialViewResult TreatmentReport(TreatmentReportSearchViewModel model)
        {

            if (User.IsInRole("Stylist"))
            {
                model.StylistId = User.Identity.GetUserId();
            }
            var report = new Logic().GetTreatmentReport<TreatmentReportViewModel>(model).ResultList;
            ViewBag.dashboardView = model.DashboardView ? true : false;
            return PartialView(report);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult GetInvoiceReport()
        {
            return View();
        }

        public PartialViewResult InvoiceReport(InvoiceReportSearchViewModel model)
        {
            if (User.IsInRole("Stylist"))
            {
                model.StylistId = User.Identity.GetUserId();
            }
            model.DateTime = (model.DateTime == new DateTime() ? DateTime.Today : model.DateTime);
            model.EndingDateTime = (model.EndingDateTime == new DateTime() ? DateTime.Today.AddDays(7) : model.EndingDateTime);
            var report = new Logic().GetInvoiceReport<InvoiceReportViewModel>(model).ResultList;
            ViewBag.dashboardView = model.DashboardView ? true : false;
            return PartialView(report);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult GetClientPointReport()
        {
            return View();
        }

        public PartialViewResult ClientPointReport(ClientPointReportSearchViewModel model)
        {
            var report = new Logic().GetClientPointReport<ClientPointReportViewModel>(model).ResultList;
            ViewBag.dashboardView = model.DashboardView ? true : false;
            return PartialView(report);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult GetStylistCommissionReport()
        {
            return View();
        }

        public PartialViewResult StylistCommissionReport(StylistCommissionReportSearchViewModel model)
        {

            if (User.IsInRole("Stylist"))
            {
                model.StylistId = User.Identity.GetUserId();
            }
            model.DateTime = (model.DateTime == new DateTime() ? DateTime.Today : model.DateTime);
            model.EndingDateTime = (model.EndingDateTime == new DateTime() ? DateTime.Today.AddDays(1) : model.EndingDateTime);
            var report = new Logic().GetStylistCommissionReport<StylistCommissionReportViewModel>(model).ResultList;
            ViewBag.dashboardView = model.DashboardView ? true : false;
            return PartialView(report);
        }

        public PartialViewResult GetPresentUsers(string role, string action)
        {
            var result = new Logic().GetPresentUsers(role, action);
            ViewBag.role = role;
            if (User.IsInRole("Stylist") && role == "Stylist")
            {
                var userEmail = new Helpers.LoggedInUserInfo().GetLoggedInUser().Email;
                result = result.Where(m => m.Email == userEmail).ToList();
            }
            return PartialView(result);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult GetClientTreatmentHistory(string id)
        {
            ViewBag.id = id;
            var appointments = new Logic().GetAppointments<AppointmentViewModel>(new AppointmentSearchViewModel { ClientId = id, AppointmentTreatmentStatus = AppointmentTreatmentStatus.Ended, Status = AppointmentStatus.Completed }).ResultList;

            return View(appointments);
        }

        public JsonResult ValidateEmailFromDatabase(string Email, string Id)
        {
            var result = new Logic().GetUsers<RegisterViewModel>(new AccountSearchViewModel { Email = Email, GetAllResults = true }).ResultList;
            if (result.Count() > 0)
            {
                if (result.FirstOrDefault().Active && result.FirstOrDefault().Id != Id)
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

BarberShop/Views/Report/GetClientPointReport.cshtml
@model Models.ViewModels.ClientPointReportSearchViewModel

@{
    ViewBag.Title = "GetClientPointReport";
    Layout = "~/Views/Shared/CustomTheme/_UserListLayout.cshtml";

}

<h2>GetClientPointReport</h2>

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Client Points Report</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="breadcrumb-item active">Client Points Report</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->

        <div class="row filter-div">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title m-b-0">Client Point Report Filters</h5>
                        <hr />
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="col-sm-12">Client</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(m => m.ClientId, new List<SelectListItem>(), "Select client", new { @id = "client-name", @class = "form-control client-name", @placeholder = "Enter client" })
                                    @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <div class="col-sm-12">

                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <hr>
                                <div class="col-md-12">
                                    <button name="Submit" class="submit-button btn btn-info waves-effect waves-light m-r-10" style="float:right">Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row loader-div">
            <div class="col-sm-12">
                <img src="~/images/report-loader.gif" alt="Alternate Text" style="background:none" />
            </div>
        </div>

        <div class="row report-div">
        </div>
    </div>
</div>


@section Styles{
    @Styles.Render("~/Content/Select2DropDown")
    @Styles.Render("~/Content/DataTable")
    @*@Styles.Render("~/Content/BootstrapDateTimePicker")*@
}

@section Scripts{
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/Select2")
    @*@Scripts.Render("~/bundles/BootstrapDateTimePicker")*@
}
<script>
    $(function () {
        $(".report-div").hide();
        $(".loader-div").hide();

        InitializeSelect2();
        $(".submit-button").on("click", function () {
            var data = {
                ClientId: $(".client-name").val(),
                DashboardView: true
            };
            $.ajax({
                type: "post",
                url: "@Url.Action("ClientPointReport", "Report")",
                data: { model: data },
                beforeSend: function () {
                    $(".filter-div").hide(1000);
                    $(".loader-div").show(1000);
                },
                success: function (data) {
                    $(".loader-div").hide(1000);
                    if (!data) {
                        $(".report-div").html("No data found");
                    }
                    else {
                        $(".report-div").html(data);
                        $("#myTable").DataTable();
                        $(".report-div").show(2000).delay(3000);
                    }
                }
            });

        });
        function InitializeSelect2() {
            var pageSize = 20;
            var optionListUrl = '@Url.Action("GetUsers", "Appointment")';
            //
            //
            //Method which is to be called for populating options in dropdown //dynamically

            var id = ".client-name";
            var url = "@Url.Action("GetUsers", "Appointment")";
            var dataArray = function (params) {
                params.page = params.page || 1;
                return {
                    prefix: params.term,
                    pageSize: pageSize,
                    pageNumber: params.page
                }
            };
            Select2AutoCompleteAjax(id, url, dataArray, pageSize,"Select Client")


        }
    });
</script>

BarberShop/Views/Report/GetInvoiceReport.cshtml
@model Models.ViewModels.InvoiceReportSearchViewModel

@{
    ViewBag.Title = "GetInvoiceReport";
    Layout = "~/Views/Shared/CustomTheme/_UserListLayout.cshtml";
}

<h2>GetInvoiceReport</h2>

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Invoice Report</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="breadcrumb-item active">Invoice Report</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->

        <div class="row filter-div">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title m-b-0">Invoice Report Filters</h5>
                        <hr />
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="col-sm-12">Client</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(m => m.ClientId, new List<SelectListItem>(), "Select client", new { @id = "client-name", @class = "form-control client-name", @placeholder = "Enter client" })
                                    @Html.ValidationMessageFor(model => model.ClientName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <div class="col-sm-12">

                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label class="col-sm-12">Start date</label>
                                <div class="col-md-12">
                                    <input type="text" onfocus="(this.type='date')" onblur="(this.type ='text')" name="DateTime" id="DateTime" class="form-control start-date" placeholder="Enter start date" value="" />
                                    @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="col-sm-12">End date</label>
                                <div class="col-sm-12">
                                    <input type="text" onfocus="(this.type='date')" onblur="(this.type ='text')" name="EndingDateTime" id="EndingDateTime" class="form-control end-date" placeholder="Enter end date" value="" />
                                    @Html.ValidationMessageFor(m => m.EndingDateTime, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <hr>
                                <div class="col-md-12">
                                    <button name="Submit" class="submit-button btn btn-info waves-effect waves-light m-r-10" style="float:right">Search</button>
                                </div>
                            </div>
                        </div>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
        <div class="row loader-div">
            <div class="col-sm-12">
                <img src="~/images/report-loader.gif" alt="Alternate Text" style="background:none" />
            </div>
        </div>

        <div class="row report-div">
        </div>
    </div>
</div>


@section Styles{
    @Styles.Render("~/Content/Select2DropDown")
    @*@Styles.Render("~/Content/DataTable")*@
    @*@Styles.Render("~/Content/BootstrapDateTimePicker")*@
}

@section Scripts{
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/Select2")
    @*@Scripts.Render("~/bundles/BootstrapDateTimePicker")*@
}
<script>
    $(function () {
            $(".report-div").hide();
        $(".loader-div").hide();

        InitializeSelect2();
        $(".submit-button").on("click", function () {
            var data = {
                ClientId: $(".client-name").val(),
                DateTime: $(".start-date").val(),
                EndingDateTime: $(".end-date").val(),
                DashboardView: true
            };
            $.ajax({
                type: "post",
                url: "@Url.Action("InvoiceReport", "Report")",
                data: { model: data },
                beforeSend: function () {
                    $(".filter-div").hide(1000);
                    $(".loader-div").show(1000);
                },
                success: function (data) {
                    $(".loader-div").hide(1000);
                    if (!data) {
                        $(".report-div").html("No data found");
                    }
                    else {
                        $(".report-div").html(data);
                        $("#myTable").DataTable();
                        $(".report-div").show(2000).delay(3000);
                    }
                }
            });

        });
        function InitializeSelect2() {
            var pageSize = 20;
            var optionListUrl = '@Url.Action("GetUsers", "Appointment")';
            //
            //
            //Method which is to be called for populating options in dropdown //dynamically

            var id = ".client-name";
            var url = "@Url.Action("GetUsers", "Appointment")";
            var dataArray = function (params) {
                params.page = params.page || 1;
                return {
                    prefix: params.term,
                    pageSize: pageSize,
                    pageNumber: params.page
                }
            };
            Select2AutoCompleteAjax(id, url, dataArray, pageSize,"Select Client")


        }
    });
</script>

BarberShop/Views/Report/GetPresentUsers.cshtml
@model IEnumerable<Models.ViewModels.UserAttendanceViewModel>
    @{ 
        var recordIndex = 1;
    }

<div class="table-responsive">
    @if (Model != null && Model.Count() > 0)
    {
        <table class="table dashboard-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Login Time</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@recordIndex</td>
                        <td>@item.Name</td>
                        <td>@item.Email</td>
                        <td>@item.AttendanceDate</td>
                    </tr>

                    { recordIndex = recordIndex + 1; }
                }

            </tbody>
        </table>
    }
    else
    {
        <hr />
        <h3>No @ViewBag.role online.</h3>
    }

</div>