BarberShop/Controllers/AppointmentApprovalController.cs
using BusinessLogic;
using Enums;
using Microsoft.AspNet.Identity;
using Models.Identity;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BarberShop.Controllers
{
    public class AppointmentApprovalController : Controller
    {
        // GET: AppointmentApproval
        [Authorize(Roles ="Administrator, SuperAdministrator")]
        public ActionResult Create(Guid id)
        {
            return View(new Logic().GetApprovals<AppointmentApprovalViewModel>(new AppointmentApprovalSearchViewModel { AppointmentId = id }).ResultList.First());
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        [HttpPost]
        public ActionResult Create(AppointmentApprovalViewModel model)
        {
            model.Approval.ApproverId = User.Identity.GetUserId();
            var result = new Logic().Create(model);
            if(result != new Guid())
            {
                return RedirectToAction("Index", "Appointment", new { Status = Enums.AppointmentStatus.Processing, AppointmentTreatmentStatus = Enums.AppointmentTreatmentStatus.Paused, CalledFor = "Unapproved Treatments", NotIndex = true });
            }
            return View(model);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Edit(Guid id)
        {
            var result = new Logic().GetApprovals<AppointmentApprovalViewModel>(new AppointmentApprovalSearchViewModel { AppointmentId = id }).ResultList.First();
            result.Action = "Edit";
            return View("Create", result);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Edit(AppointmentApprovalViewModel model)
        {
            model.Approval.LastUpdatedOn = DateTime.Now;
            var result = new Logic().Edit(model);
            if(result != new Guid())
            {
                var statusStr = string.Format("{0},{1},{2}", AppointmentTreatmentStatus.Pending.ToString(), AppointmentTreatmentStatus.Paused.ToString(), AppointmentTreatmentStatus.Started.ToString());
                return RedirectToAction("Index", "Appointment", new { ClientId = model.Client.Id, SkipDateCheck = true, Status = AppointmentStatus.Approved, TreatmentStatuses = statusStr, NotIndex = true, IsEditAllowed = true });
            }

            else
            {
                return View("Create", result); 
            }

        }

        [HttpPost]
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Delete(AppointmentApprovalViewModel model)
        {
            var result = new Logic().Delete(model);
            if(result != new Guid())
            {
                return RedirectToAction("Index", "Appointment");
            }
            else
            {
                return RedirectToAction("Create", model);
            }
        }
    }
}

BarberShop/Views/AppointmentApproval/Create.cshtml
@model Models.ViewModels.AppointmentApprovalViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/CustomTheme/_UserListLayout.cshtml";
    var action = string.IsNullOrEmpty(Model.Action) ? "Create" : "Edit";
}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">@action Approval</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="breadcrumb-item active">@action Approval</li>
                    </ol>
                    <button type="button" class="btn btn-info d-none d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> Create New</button>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Basic Information</h5>
                        @using (Html.BeginForm(action, "AppointmentApproval", FormMethod.Post, new { @class = "form-horizontal form-material", @enctype = "multipart/form-data" }))
                        {

                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="col-md-12" for="example-text">
                                    <span> Client</span>
                                </label>
                                <div class="col-md-12">
                                    @Model.Client.Name
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12" for="example-text">
                                    <span> Treatment</span>
                                </label>
                                <div class="col-md-12">
                                    @Model.Treatment.Name
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12" for="example-text">
                                    <span> Stylist</span>
                                </label>
                                <div class="col-md-12">
                                    @Model.Stylist.Name
                                    @Html.HiddenFor(m => m.Appointment.Id)
                                    @Html.HiddenFor(m => m.Approver.Id)
                                    @Html.HiddenFor(m => m.Client.Id)
                                    @Html.HiddenFor(m => m.Stylist.Id)
                                    @Html.HiddenFor(m => m.Treatment.Id)
                                </div>
                            </div>
                            @*<div class="form-group">
                                <label class="col-md-12" for="example-text">
                                    <span>Appointment Status</span>
                                </label>
                                <div class="col-md-12">
                                    @Html.EnumDropDownListFor(model => model.Approval.Status, "--Select--", new { @class = "form-control status-dropdown" })
                                    @Html.ValidationMessageFor(model => model.Approval.Status, "", new { @class = "text-danger" })
                                </div>
                            </div>*@
                            <div class="form-group">
                                <label class="col-md-12" for="example-text">
                                    <span>Treatment Status</span>
                                </label>
                                <div class="col-md-12">
                                    @Html.EnumDropDownListFor(model => model.Appointment.Status, "--Select--", new { @class = "form-control status-dropdown" })
                                    @Html.ValidationMessageFor(model => model.Appointment.Status, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Submit</button>
                            @*if (action != "Create")
                            {
                                <button type="button" id="delete" class="btn btn-info waves-effect waves-light m-r-10" onclick="javascript:document.getElementById('delete-form').submit();">Delete</button>
                            }*@
                            <button type="button" class="btn btn-inverse waves-effect waves-light cancel-btn">Cancel</button>
                        }
                        @using (Html.BeginForm("Delete", "AppointmentApproval", Model, FormMethod.Post, new { id = "delete-form" }))
                        {
                            @Html.AntiForgeryToken()
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}