BarberShop/Controllers/AppointmentController.cs
using AutoMapper;
using BusinessLogic;
using Enums;
using Helpers.Select2;
using Microsoft.AspNet.Identity;
using Models;
using Models.Identity;
using Models.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Script.Serialization;

namespace BarberShop.Controllers
{
    public class AppointmentController : Controller
    {
        // GET: Appointment
        public ActionResult Index(AppointmentSearchViewModel model)
        {
            if (!string.IsNullOrEmpty(model.TreatmentStatuses))
            {
                try
                {
                    model.MultiAppointmentTreatmentStatus = new List<int>();
                    foreach (var s in model.TreatmentStatuses.Split(','))
                    {
                        model.MultiAppointmentTreatmentStatus.Add((int)Enum.Parse(typeof(AppointmentTreatmentStatus), s));
                    }
                }
                catch
                {

                }
            }
            //added for stylish dashboard, as no authorization is required for that view, therefore this acts as a bypass.
            PartialViewResult check;
            var userId = User.Identity.GetUserId();
            if (Request.UrlReferrer != null)
            {
                var url = Request.UrlReferrer.AbsolutePath;
                if (User.IsInRole("SuperAdministrator") || User.IsInRole("Administrator") || url.Contains("Dashboard"))
                {
                    return View(GetAppointments(model).Model);
                }
                else if (User.IsInRole("Stylist"))
                {
                    model.StylistId = userId;
                }
                else if (User.IsInRole("Client"))
                {
                    model.ClientId = userId;
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            check = GetAppointments(model);
            return View(check.Model);
        }

        public ActionResult AppointmentDashboard()
        {
            var stylistId = User.IsInRole("Stylist") ? User.Identity.GetUserId() : "";
            var stylists = new Logic().GetUsers<RegisterViewModel>(new AccountSearchViewModel { Id = stylistId, RoleId = new Logic().GetRoleId<RoleViewModel>(new RoleSearchViewModel { Name = "Stylist" }).ResultList.FirstOrDefault().Id }).ResultList.GroupBy(x => x.Email).Select(o => o.FirstOrDefault());
            var model = new FullCalendarSchedular { events = new List<FullCalendarEvents>(), resources = new List<FullCalendarResources>() };
            model.resources = stylists.Select(m => new FullCalendarResources { id = m.Id, title = m.Name, eventColor = "transparent" }).Distinct().ToList();
            return View(model);
        }


        public ActionResult AppointmentDetails(FullCalendarEvents EventModel)
        {
            return PartialView("_AppointmentDetails", EventModel);
        }
        public ActionResult AppointmentToolTip(FullCalendarEvents EventModel)
        {
            return PartialView("_AppointmentToolTip", EventModel);
        }

        [Authorize(Roles = "Administrator, SuperAdministrator, Stylist")]
        public ActionResult Create()
        {
            ViewBag.ViewFor = "Create Appointment";
            return View(new AppointmentViewModel { BookingDate = DateTime.Now, AppointmentStartingTime = DateTime.Now, Action = "Create", Client = new ApplicationUser(), ClientsList = new List<SelectListItem>(), StylistsList = new List<SelectListItem>(), TreatmentsList = new List<SelectListItem>() });
        }

        public PartialViewResult CreatePartial(AppointmentViewModel model)
        {
            return PartialView(model);
        }
        public PartialViewResult CreatePartialModal(Guid? Id, DateTime? Date, Guid? StylistId)
        {
            ViewBag.ViewFor = Id == null || Id == new Guid() ? "Modal Create" : "Modal Edit";
            var BookingDate = Date ?? DateTime.Now;
            var stylist = StylistId != null || StylistId != new Guid() ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = StylistId.ToString(), Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            AppointmentViewModel model = new AppointmentViewModel { BookingDate = BookingDate, AppointmentStartingTime = BookingDate, Action = "Create", Client = new ApplicationUser(), ClientsList = new List<SelectListItem>(), StylistsList = stylist, TreatmentsList = new List<SelectListItem>() };
            if (Id != null)
            {
                var AppointmentId = Id ?? new Guid();
                model = new Logic().GetAppointments<AppointmentViewModel>(new AppointmentSearchViewModel { Id = AppointmentId, StartingDateTime = BookingDate, EndingDateTime = BookingDate.AddDays(1).AddMilliseconds(-10), Select2 = false }).ResultList.First();
                model.Action = "Edit";
                model.ClientsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Client.Id, Text = model.Client.Name, Selected = true }) };
                model.TreatmentsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Treatment.Id.ToString(), Text = model.Treatment.Name, Selected = true }) };
                model.StylistsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Stylist.Id, Text = model.Stylist.Name, Selected = true }) };
            }
            model.IsDashboard = true;
            return PartialView("CreatePartial", model);
        }

        public PartialViewResult CreatePartialForStart(Guid? Id, DateTime? Date, string ClientId, string StylistId, DateTime? LastAppointmentEndingDateTime)
        {

            var BookingDate = Date ?? DateTime.Now.Date;
            var lastAppointmentEndingDateTime = LastAppointmentEndingDateTime ?? DateTime.Now;
            ViewBag.ViewFor = Id == null || Id == new Guid() ? "Start Create" : "Start Edit";
            var stylist = !string.IsNullOrEmpty(StylistId) ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = StylistId, Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            var client = !string.IsNullOrEmpty(ClientId) ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = ClientId, Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            AppointmentViewModel model = new AppointmentViewModel { BookingDate = BookingDate, AppointmentStartingTime = lastAppointmentEndingDateTime, Action = "Create", Client = new ApplicationUser { Name = client.FirstOrDefault().Text, Id = ClientId }, ClientId = ClientId, StylistId = StylistId, ClientsList = client, Stylist = new ApplicationUser { Id = StylistId, Name = stylist.FirstOrDefault().Text }, StylistsList = stylist, TreatmentsList = new List<SelectListItem>() };
            if (Id != null)
            {
                var AppointmentId = Id ?? new Guid();
                model = new Logic().GetAppointments<AppointmentViewModel>(new AppointmentSearchViewModel { Id = AppointmentId, StartingDateTime = BookingDate, EndingDateTime = BookingDate.AddDays(1).AddMilliseconds(-10), Select2 = false }).ResultList.First();
                model.Action = "Edit";
                model.ClientsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Client.Id, Text = model.Client.Name, Selected = true }) };
                model.TreatmentsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Treatment.Id.ToString(), Text = model.Treatment.Name, Selected = true }) };
                model.StylistsList = new List<SelectListItem>() { (new SelectListItem { Value = model.Stylist.Id, Text = model.Stylist.Name, Selected = true }) };
            }
            model.IsDashboard = true;
            model.IsForStart = true;
            return PartialView("CreatePartial", model);
        }

        public PartialViewResult CreateMultiTreatmentAppointment(string StylistId)
        {

            var BookingDate = DateTime.Now.Date;
            var currentDateTime = DateTime.Now;
            var stylist = !string.IsNullOrEmpty(StylistId) ? new Logic().GetUsers<Select2OptionModel>(new AccountSearchViewModel { Id = StylistId, Select2 = true }).ResultList.Select(m => new SelectListItem { Text = m.text, Value = m.id }).ToList() : new List<SelectListItem>();
            AppointmentViewModel model = new AppointmentViewModel
            {
                BookingDate = BookingDate,
                AppointmentStartingTime = currentDateTime,
                AppointmentEndingTime = currentDateTime,
                ActualStartingTime = currentDateTime,
                ActualEndingTime = currentDateTime,
                Action = "Create",
                StylistId = StylistId,
                Stylist = new ApplicationUser
                {
                    Id = StylistId,
                    Name = stylist.FirstOrDefault().Text
                }
            };
            return PartialView("_MultiTreatmentAppointment", model);
        }

        [HttpPost]
        public ActionResult Create(AppointmentViewModel model)
        {
            ViewBag.ViewFor = "Create Appointment";
            model.Approver = new ApplicationUser { Id = User.Identity.GetUserId() };
            var result = new Logic().Create(model);
            return Json(result != new Guid(), JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public ActionResult CreateMultiAppointment(AppointmentViewModel model)
        {
            model.Approver = new ApplicationUser { Id = User.Identity.GetUserId() };

BarberShop/Controllers/TaxController.cs
using BusinessLogic;
using Helpers.Select2;
using Models;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BarberShop.Controllers
{
    public class TaxController : BaseController
    {
        // GET: Tax
        public ActionResult Index()
        {
            return View(new Logic().GetTaxes(new Guid()));
        }

        // GET: Tax/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Tax/Create
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Create()
        {
            return View(new TaxViewModel { Action = "Create" });
        }

        // POST: Tax/Create
        [HttpPost]
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Create(TaxViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                var result = new Logic(LoggedInUserId).Create(model);
                if (result != new Guid())
                    return RedirectToAction("Index");
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Tax/Edit/5
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Edit(Guid id)
        {
            var tax = new Logic().GetTax(id);
            tax.Action = "Edit";
            return View("Create", tax);
        }

        // POST: Tax/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Edit(TaxViewModel model)
        {
            try
            {
                // TODO: Add update logic here
                var result = new Logic(LoggedInUserId).Edit(model);
                if(result != new Guid())
                return RedirectToAction("Index");
                return View("Create", model);
            }
            catch
            {
                return View("Create", model);
            }
        }

        // GET: Tax/Delete/5
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Delete(Guid id)
        {
            var check = new Logic().Delete(new TaxViewModel { Id = id });
                return RedirectToAction("Index");
        }

        public PartialViewResult _DeleteModal(Guid id)
        {
            var result = new Logic().GetTax(id);
            return PartialView(result);
        }


        #region JSON methods

        public JsonResult GetTaxesForSelect2(string prefix, int pageSize, int pageNumber)
        {
            var result = new Logic().GetTaxes(new Guid()).Select(m => new Select2OptionModel { id = m.Id.ToString(), text = m.Name }).ToList();
            return Json(new Select2Repository().GetSelect2PagedResult(pageSize, pageNumber, result), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Helping Methods



        #endregion
    }
}

BarberShop/Views/Product/Create.cshtml
@model Models.ViewModels.ProductViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/CustomTheme/_UserListLayout.cshtml";
    var action = Model.Action;
    var categoryList = Model.Action == "Edit" ? new List<SelectListItem> { new SelectListItem { Value = Model.Category.Id.ToString(), Text = Model.Category.Name } } : new List<SelectListItem>();
    var taxList = Model.Action == "Edit" ? new List<SelectListItem> { new SelectListItem { Value = Model.Tax.Id.ToString(), Text = Model.Tax.Name } } : new List<SelectListItem>();
}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Create Product</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="breadcrumb-item active">@action Product</li>
                    </ol>
                    <button type="button" class="btn btn-info d-none d-lg-block m-l-15" onclick="window.location.href='@Url.Action("Create", "Product")'"><i class="fa fa-plus-circle"></i> Create New</button>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Basic Information</h5>
                        @using (Html.BeginForm(action, "Product", FormMethod.Post, new { @class = "form-horizontal form-material", @enctype = "multipart/form-data", autocomplete = "off" }))
                        {

                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                <label class="col-md-12" for="example-text">
                                    <span> Name</span>
                                </label>
                                <div class="col-md-12">
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Enter Product name" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">Product Image</label>
                                <div class="col-sm-12">
                                    <img class="img-responsive" src="@Model.ImageUrl" id="image-thumbnail" alt="" style="max-width:120px;">
                                </div>
                                <div class="col-sm-12">
                                    <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                        <div class="form-control" data-trigger="fileinput"> <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div> <span class="input-group-addon btn btn-default btn-file">
                                            <input type="file" name="Image" id="Image" onchange="ShowImage(this)">
                                        </span> <a href="javascript:void(0)" class="input-group-addon btn btn-default fileinput-exists" onclick='document.getElementById("Image").value = "";' data-dismiss="fileinput">Remove</a>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12" for="example-email">
                                    <span>Price (Inclusive of Tax)</span>
                                </label>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", type = "text", placeholder = "Enter price" } })
                                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <label class="col-md-12" for="example-phone">
                                    <span>Category</span>
                                </label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(m => m.CategoryId, categoryList, new { @id = "category-name", @class = "form-control category-name" })
                                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <label class="col-md-12" for="example-phone">
                                    <span>Tax</span>
                                </label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(m => m.TaxId, taxList, new { @id = "tax-name", @class = "form-control tax-name" })
                                    @Html.ValidationMessageFor(model => model.TaxId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-12">Description</label>
                                <div class="col-sm-12">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", placeholder = "Enter description" })
                                    @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <button type="submit" class="btn btn-info waves-effect waves-light m-r-10">Submit</button>
                            <button type="button" class="btn btn-inverse waves-effect waves-light cancel-btn">Cancel</button>
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
</div>
<link href="~/Content/CustomCss/test.css" rel="stylesheet" />

<script>

    $(function () {

        InitializeSelect2();

        $("body").on("click", "#category-name", function () {
            InitializeSelect2();
        });

       
    });
    function ShowImage(input) {


        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image-thumbnail').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
        //var thumbnail = $("#Image").val();
        //$("#image-thumbnail").attr("src", thumbnail);

    }

    function InitializeSelect2() {
                    var pageSize = 20;
            var optionListUrl = '@Url.Action("GetCategoriesForSelect2", "ProductCategory")';
            //
            //
            //Method which is to be called for populating options in dropdown //dynamically

            var id = "#category-name";
            var url = "@Url.Action("GetCategoriesForSelect2", "ProductCategory")";
            var dataArray = function (params) {
                params.page = params.page || 1;
                return {
                    prefix: params.term,
                    pageSize: pageSize,
                    pageNumber: params.page
                }
            };
        Select2AutoCompleteAjax(id, url, dataArray, pageSize, "Select Category");

            var id = "#tax-name";
            var url = "@Url.Action("GetTaxesForSelect2", "Tax")";
            var dataArray = function (params) {
                params.page = params.page || 1;
                return {
                    prefix: params.term,
                    pageSize: pageSize,
                    pageNumber: params.page
                }
            };
        Select2AutoCompleteAjax(id, url, dataArray, pageSize,"Select Tax");
    }
</script>

@section Scripts{
    @Scripts.Render("~/bundles/Select2")
    @Scripts.Render("~/bundles/jqueryval")
}

@section Styles{
    @Styles.Render("~/Content/Select2DropDown")
}

BarberShop/Views/Product/Index.cshtml
@model Models.ViewModels.ProductSearchViewModel
@using Models.ViewModels;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/CustomTheme/_UserListLayout.cshtml";
}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Product</h4>
            </div>
            <div class="col-md-7 align-self-center text-right">
                <div class="d-flex justify-content-end align-items-center">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li class="breadcrumb-item active"><a href="@Url.Action("Index","Product")">Product</a></li>
                    </ol>
                    @if (User.IsInRole("SuperAdministrator") || User.IsInRole("Administrator"))
                    {
                        <button type="button" class="btn btn-info d-none d-lg-block m-l-15" onclick='window.location.href="@Url.Action("Create", "Product")"'><i class="fa fa-plus-circle"></i> Create New</button>
                    }
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- .row -->

        <div class="row filter-div">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title m-b-0">Product Filters</h5>
                        <hr />
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="col-sm-12">Name</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(m => m.Id, new List<SelectListItem>(), "Select Product", new { @id = "product-name", @class = "form-control product-name", @placeholder = "Select product" })
                                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*<div class="form-group col-md-5">
                                <label class="col-sm-12">Stylist</label>
                                <div class="col-md-12">
                                    @Html.DropDownListFor(m => m.Id, new List<SelectListItem>(), "Select stylist", new { @id = "stylist-name", @class = "form-control stylist-name", @placeholder = "Enter stylist" })
                                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                            <div class="form-group col-md-12">
                                <div class="col-md-12 mt-2">
                                    <button name="Submit" class="submit-button btn btn-info waves-effect waves-light @*m-r-10*@" style="float:right">Search</button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row loader-div">
            <div class="col-sm-12">
                <img src="~/images/report-loader.gif" alt="Alternate Text" style="background:none" />
            </div>
        </div>


        <div class="card-deck report-div p-b-20">
            @Html.Action("_IndexPartial", "Product")
        </div>



    </div>


</div>

<!-- Modal -->
<div class="modal bd-example-modal-lg fade" tabindex="-1" id="productModal" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" id="modal-dialog">

    </div>
</div>


@section Styles{
    @Styles.Render("~/Content/Select2DropDown")
    @Styles.Render("~/Content/DataTable")
    @*@Styles.Render("~/Content/BootstrapDateTimePicker")*@
}

@section Scripts{
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/Select2")
    @*@Scripts.Render("~/bundles/BootstrapDateTimePicker")*@
}
<script src="~/Scripts/CustomScripts/search-filters-methods.js"></script>
<script>
    $(function () {
      InitialOrientation();
        InitializeSelect2();
        $(".submit-button").on("click", function () {
            var id = $(".product-name").val();
            var stylist = $(".stylist-name").val();

            var data = {
                Id: id,
                StylistId: stylist,
                Select2: true,
            };
           var url = "@Url.Action("_IndexPartial", "Product")";
           GetSearchFilterAjaxResult(url, data, false);

        });
        function InitializeSelect2() {
            var pageSize = 20;
            var optionListUrl = '@Url.Action("GetUsers", "Appointment")';
            //
            //
            //Method which is to be called for populating options in dropdown //dynamically

            var id = ".product-name";
            var url = "@Url.Action("GetProductsForSelect2", "Product")";
            var dataArray = function (params) {
                params.page = params.page || 1;
                return {
                    prefix: params.term,
                    pageSize: pageSize,
                    pageNumber: params.page
                }
            };
            Select2AutoCompleteAjax(id, url, dataArray, pageSize,"Select Product")

            var id = ".stylist-name";
            var url = "@Url.Action("GetStylists", "Appointment")";
            var dataArray = function (params) {
                params.page = params.page || 1;
                return {
                    prefix: params.term,
                    pageSize: pageSize,
                    pageNumber: params.page
                }
            };
            Select2AutoCompleteAjax(id, url, dataArray, pageSize,"Select Stylist")
        }
    });
</script>